### ISSUE TITLE
nothing appeared in the demo.html you provide

### ISSUE THREAD

**Issue by portwatcher** [lvming6816077/MLogger#1]
I want to integrate it with our mobile Web browser product. http://yunji.one

After open it with Chrome, nothing appeared.

![image](https://cloud.githubusercontent.com/assets/2919533/12194589/21665f54-b62c-11e5-84a8-dbfad602bf1c.png)

How can I open the log panel?

**Comment by potcode** [comment]
I meet the same problem

**Comment by portwatcher** [comment]
You need to draw a line on the simulated screen or real screen as indicated in README.

![image](https://cloud.githubusercontent.com/assets/2919533/12286991/048d95c4-ba04-11e5-8f70-a58eae0485ca.png)

Then it will appear.

![image](https://cloud.githubusercontent.com/assets/2919533/12287000/15a35b32-ba04-11e5-86bb-304b47be455a.png)

If you want to customize your triggering way, just pass your implementation of `triggerLog` in when init.

**Comment by potcode** [comment]
It worked, thank you。😄
